### ISSUE TITLE
Running workflow cannot be canceled after system reboot

### ISSUE THREAD

**Issue by bri365** [StackStorm/st2#2838]
We have a repeatable situation where running action-chain workflows cannot be canceled after hard system reset.
- 'st2 execution list' shows workflows as running
- children actions are either 'succeeded' or 'canceled'
- 'st2 execution cancel' command returns: Action cannot be canceled. State = succeeded.

Currently running 1.3.2

[cannot-cancel-workflow.txt](https://github.com/StackStorm/st2/files/386434/cannot-cancel-workflow.txt)

**Comment by lakshmi-kannan** [comment]
I think this is fixed in 1.4. FYI, here are the related PRs

https://github.com/StackStorm/st2/pull/1937
https://github.com/StackStorm/st2/pull/2273
https://github.com/StackStorm/st2/pull/2369
https://github.com/StackStorm/st2/pull/2371
https://github.com/StackStorm/st2/pull/2383

**Comment by lakshmi-kannan** [comment]
As per our slack conversation, please verify if issue still persists in 1.5.1. We can look into it if you still see the issue. I am closing this issue now.

**Comment by bri365** [comment]
@lakshmi-kannan 
Hurray!  We're on 1.6.0! 👍 
Boo! The problem still exists:
[root@sonic-connect ~]# st2 execution get 57adb8ab3de79f0a2ae20185
id: 57adb8ab3de79f0a2ae20185
status: running (26251s elapsed)
parameters:
  change_set: []
  event_action: Something
  thing: vx15420
  previous_references: []
  thing_uuid: apples-2-apples
result: None
[root@sonic-connect ~]# st2 execution cancel 57adb8ab3de79f0a2ae20185
Action cannot be canceled. State = succeeded.

Mongo agrees:
"status" : "running",

Where to look next?

This is a child action of an action chain workflow:
[root@sonic-connect ~]# st2 execution get 57adb8563de79f09877a7f0e
id: 57adb8563de79f09877a7f0e
action.ref: connect.do_something_interesting
parameters:
  change_set: []
  event_action: Created
  thing: vx15420
  previous_references: []
  thing_uuid: apples-2-apples
status: running (27523s elapsed)
start_timestamp: 2016-08-12T11:51:50.297118Z
end_timestamp: None
```
+--------------------------+--------------------------+-----------+--------------------------+-------------------------------+
| id                       | status                   | task      | action                   | start_timestamp               |
+--------------------------+--------------------------+-----------+--------------------------+-------------------------------+
| 57adb8ab3de79f0a2ae20185 | running (27438s elapsed) | action_1  | pack1.action_1           | Fri, 12 Aug 2016 11:53:15 UTC |
| 57adb8af3de79f0a2ae20192 | canceled                 | action_2  | pack2.action_2           | Fri, 12 Aug 2016 11:53:19 UTC |
+--------------------------+--------------------------+-----------+--------------------------+-------------------------------+
```

**Comment by Kami** [comment]
Is it a mistral workflow?

If so, I encountered some similar issues when testing and working on the v1.6.0 release, but I didn't have time to dig in yet (from top of my head it looked related to mistral and / or results tracker).

**Comment by bri365** [comment]
Nope, just a plain old action chain

**Comment by bri365** [comment]
I'm instrumenting st2api/controllers/v1/actionexecutions.py with additional logging of liveaction_db to see what's coming back.  What I don't yet know, is how chains, parents, and children are handled.  I wonder if the order in which I'm canceling actions after hard reboot makes a difference.

**Comment by bri365** [comment]
@lakshmi-kannan - can you re-open this?
