### ISSUE TITLE
st2 python3 interpreter is falling back to importing a python2 lib that is incompatible with python3 similar to #4658

### ISSUE THREAD

**Issue by blourdel** [StackStorm/st2#4710]
##### SUMMARY
python3 action calls python2 packages on import
similar to #4658

##### ISSUE TYPE
 - Bug Report

##### STACKSTORM VERSION
st2 3.0.1, on Python 3.6.8

##### OS / ENVIRONMENT / INSTALL METHOD
oneline install
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

##### STEPS TO REPRODUCE
Install a local python 3 package with
cat requirement.txt
scikit-learn

create a python action
cat test.py
import sklearn
from st2common.runners.base_action import Action
class NextPoint(Action):
    def run(self):
          return

##### EXPECTED RESULTS
I expected the action to run to completion

##### ACTUAL RESULTS
A 2.7 package is loaded causing an error

 File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 238, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/loader.py", line 168, in register_plugin
    module = imp.load_source(module_name, plugin_abs_file_path)
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/stackstorm/packs/modal2/actions/test.py", line 4, in <module>
    from sklearn.gaussian_process import GaussianProcessRegressor
  File "/opt/stackstorm/virtualenvs/modal2/lib/python3.6/site-packages/sklearn/gaussian_process/__init__.py", line 13, in <module>
    from .gpr import GaussianProcessRegressor
  File "/opt/stackstorm/virtualenvs/modal2/lib/python3.6/site-packages/sklearn/gaussian_process/gpr.py", line 16, in <module>
    from .kernels import RBF, ConstantKernel as C
  File "/opt/stackstorm/virtualenvs/modal2/lib/python3.6/site-packages/sklearn/gaussian_process/kernels.py", line 31, in <module>
    from ..metrics.pairwise import pairwise_kernels
  File "/opt/stackstorm/virtualenvs/modal2/lib/python3.6/site-packages/sklearn/metrics/__init__.py", line 7, in <module>
    from .ranking import auc
  File "/opt/stackstorm/virtualenvs/modal2/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 35, in <module>
    from ..preprocessing import label_binarize
  File "/opt/stackstorm/virtualenvs/modal2/lib/python3.6/site-packages/sklearn/preprocessing/__init__.py", line 6, in <module>
    from ._function_transformer import FunctionTransformer
  File "/opt/stackstorm/virtualenvs/modal2/lib/python3.6/site-packages/sklearn/preprocessing/_function_transformer.py", line 5, in <module>
    from ..utils.testing import assert_allclose_dense_sparse
  File "/opt/stackstorm/virtualenvs/modal2/lib/python3.6/site-packages/sklearn/utils/testing.py", line 61, in <module>
    from nose.tools import raises as _nose_raises
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/nose/core.py", line 153
    print "%s version %s" % (os.path.basename(sys.argv[0]), __version__)

**Comment by blourdel** [comment]
I tried Ubuntu Bionoc --instable --stagging
st2 3.1dev (7079635), on Python 3.6.8
and here the problem is solved.

**Comment by cognifloyd** [comment]
StackStorm no longer supports python 2 for anything. Please file a new issue of you are still experiencing any issues like this.
Thanks!
